/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/oidc/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Login
         * @description Démarre le flow authorization code + PKCE.
         */
        get: operations["login_oidc_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oidc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Callback
         * @description Callback OIDC — valide le state, échange le code, ouvre la session.
         */
        get: operations["callback_oidc_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oidc/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Efface le cookie de session — ne contacte pas l'IdP.
         */
        post: operations["logout_oidc_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oidc/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Renvoie l'identité courante depuis la session, 401 sinon.
         */
        get: operations["me_oidc_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cockpit/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cockpit Kpis
         * @description 4 KPI Cockpit + 4 séries 30 jours.
         *
         *     Source : `CaseService.list_cases()` + `AuditLog`. Le frontend Next.js
         *     rend les sparklines via Recharts/visx en réutilisant ces séries.
         */
        get: operations["cockpit_kpis_api_v1_cockpit_kpis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cockpit/top-vendors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cockpit Top Vendors
         * @description Top N fournisseurs par exposition financière, agrégé depuis les cases.
         */
        get: operations["cockpit_top_vendors_api_v1_cockpit_top_vendors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Findings
         * @description Liste paginée des findings — source : cases enrichis par leurs events.
         *
         *     Phase 0 — on agrège depuis `service.list_cases()` (qui porte `severity`,
         *     `invoice_id`, `vendor_id`) + `case_events` pour `signal` / `rule_id`.
         *     En Phase 5, une vraie table `findings` sera ajoutée.
         */
        get: operations["list_findings_api_v1_findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vendors/{vendor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vendor Summary
         * @description Fiche fournisseur 360° (version API — sans dataset session).
         *
         *     En l'absence de données chargées (free-tier strict), renvoie au moins les
         *     cases agrégés par vendor_id pour calculer l'exposition.
         */
        get: operations["vendor_summary_api_v1_vendors__vendor_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vendors/{vendor_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vendor Timeline
         * @description Timeline événements 30 jours : cases + audit log pertinents.
         */
        get: operations["vendor_timeline_api_v1_vendors__vendor_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cases V1
         * @description Liste paginée des cases avec filtres (status/severity/assignee).
         */
        get: operations["list_cases_v1_api_v1_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/comment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Case Comment */
        post: operations["case_comment_api_v1_cases__case_id__comment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/bulk/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cases Bulk Assign */
        post: operations["cases_bulk_assign_api_v1_cases_bulk_assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/bulk/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cases Bulk Close */
        post: operations["cases_bulk_close_api_v1_cases_bulk_close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rings Graph
         * @description Charge un scénario synthétique et retourne le graphe vendor↔IBAN.
         *
         *     Phase 3b — alimente la visualisation sigma.js côté Next.js sans nécessiter
         *     qu'un dataset soit uploadé en session. Réutilise les scénarios P5-2 +
         *     `detect_fraud_rings` (NetworkX).
         */
        get: operations["rings_graph_api_v1_rings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit List
         * @description Audit log paginated. `cursor` = seq de départ (exclusif).
         */
        get: operations["audit_list_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit Verify
         * @description Recalcul du hash chain + validation des signatures Ed25519 (P5-5).
         */
        get: operations["audit_verify_api_v1_audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/dossier.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Dossier Pdf
         * @description Génère et streame un dossier PDF d'enquête (weasyprint si installé).
         *
         *     Phase 0 — version minimale : renvoie un PDF placeholder via reportlab/
         *     weasyprint si disponibles, sinon un message en texte.
         */
        get: operations["export_dossier_pdf_api_v1_exports_dossier_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/llm/narrative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Llm Narrative Stream
         * @description Génère la narration d'audit ISA 240 en streaming SSE.
         *
         *     Format Server-Sent Events compatible Vercel AI SDK (`useChat`/`useCompletion`).
         *     Le front Next.js consomme via `EventSource` ou fetch streaming.
         */
        post: operations["llm_narrative_stream_api_v1_llm_narrative_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — retourne 200 si l'API est opérationnelle.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/security/public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Security Public Key
         * @description Publie la clé publique Ed25519 utilisée pour signer l'audit log (P5-5).
         *
         *     Permet à un auditeur externe (CAC, ACPR, Cour des comptes) de vérifier
         *     indépendamment les signatures du journal d'audit sans accès au backend.
         *
         *     En l'absence de clé privée configurée (mode démo), renvoie
         *     `{"public_key_b64": "", "enabled": false}`.
         */
        get: operations["security_public_key_security_public_key_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Webhook Test
         * @description Envoie un événement factice `webhook.test` vers `Settings.webhook_url`.
         *
         *     Permet de valider la configuration côté pilote en bout-en-bout
         *     (signature HMAC, retry tenacity, format CloudEvents simplifié).
         *     Renvoie un objet `{ok, status, duration_ms, event_id, type}`.
         *
         *     En l'absence de configuration (`webhook_url` vide), renvoie
         *     `{ok: false, skipped: true, reason: "disabled"}`.
         */
        post: operations["webhook_test_webhook_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect
         * @description Exécute les détecteurs sélectionnés sur le dataset de factures fourni.
         *
         *     Retourne la liste complète des findings avec leur sévérité, signal et evidence.
         */
        post: operations["detect_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/detect/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect Csv
         * @description Accepte un fichier CSV de factures et exécute les détecteurs par défaut.
         */
        post: operations["detect_csv_detect_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Score
         * @description Calcule le score de risque consolidé (0-100) par facture.
         *
         *     Utilise les poids configurés dans `weights.yaml` par défaut.
         *     Passez `detector_weights` pour surcharger à la volée.
         */
        post: operations["score_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cases
         * @description Liste les cases depuis la base de données (SQLite persistante).
         *
         *     Filtres optionnels : `status_filter` (open/closed) et `severity` (critical/high/medium/low).
         */
        get: operations["list_cases_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close Case
         * @description Clôture motivée d'un case.
         *
         *     La raison de clôture doit être non vide (≥ 10 caractères).
         *     L'événement est journalisé dans la piste d'audit SHA-256.
         */
        post: operations["close_case_cases__case_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEntryOut */
        AuditEntryOut: {
            /** Seq */
            seq: number;
            /** At */
            at: string;
            /** Actor */
            actor: string;
            /** Kind */
            kind: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Prev Hash */
            prev_hash: string;
            /** Hash */
            hash: string;
            /**
             * Signature
             * @default
             */
            signature: string;
        };
        /** AuditPage */
        AuditPage: {
            /** Entries */
            entries: components["schemas"]["AuditEntryOut"][];
            /** Total */
            total: number;
            /** Cursor Next */
            cursor_next?: number | null;
        };
        /** AuditVerifyResult */
        AuditVerifyResult: {
            /** Valid */
            valid: boolean;
            /** Invalid Seqs */
            invalid_seqs?: number[];
            /** N Total */
            n_total: number;
            /** N Signed */
            n_signed: number;
            /**
             * Public Key B64
             * @default
             */
            public_key_b64: string;
        };
        /** Body_detect_csv_detect_csv_post */
        Body_detect_csv_detect_csv_post: {
            /** File */
            file: string;
        };
        /** BulkAssignBody */
        BulkAssignBody: {
            /** Case Ids */
            case_ids: string[];
            /** Assignee */
            assignee: string;
            /** Actor */
            actor: string;
        };
        /** BulkCloseBody */
        BulkCloseBody: {
            /** Case Ids */
            case_ids: string[];
            /**
             * Status
             * @description "confirmed" | "rejected" | "false_positive"
             */
            status: string;
            /** Reason */
            reason: string;
            /** Actor */
            actor: string;
        };
        /** BulkResult */
        BulkResult: {
            /** N Ok */
            n_ok: number;
            /** N Errors */
            n_errors: number;
            /** Error Case Ids */
            error_case_ids?: string[];
        };
        /** CaseOut */
        CaseOut: {
            /** Case Id */
            case_id: string;
            /** Title */
            title: string;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
            /** Exposure Eur */
            exposure_eur: number | null;
            /** Assignee */
            assignee: string | null;
            /** Created At */
            created_at: string;
            /** Invoice Id */
            invoice_id: string | null;
            /** Vendor Id */
            vendor_id: string | null;
        };
        /** CaseOutV1 */
        CaseOutV1: {
            /** Case Id */
            case_id: string;
            /** Title */
            title: string;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
            /** Vendor Id */
            vendor_id?: string | null;
            /** Invoice Id */
            invoice_id?: string | null;
            /** Exposure Eur */
            exposure_eur?: number | null;
            /** Assignee */
            assignee?: string | null;
            /** Created At */
            created_at: string;
            /** Closed At */
            closed_at?: string | null;
            /** Closure Reason */
            closure_reason?: string | null;
        };
        /** CloseRequest */
        CloseRequest: {
            /** Reason */
            reason: string;
            /**
             * Actor
             * @default api
             */
            actor: string;
        };
        /** CockpitKPIs */
        CockpitKPIs: {
            /**
             * Exposure Total Eur
             * @description Exposition totale (€)
             */
            exposure_total_eur: number;
            /**
             * Exposure Critical Eur
             * @description Exposition CRITICAL (€)
             */
            exposure_critical_eur: number;
            /** N Cases Open */
            n_cases_open: number;
            /** N Cases Overdue */
            n_cases_overdue: number;
            /** N Cases Unassigned Critical */
            n_cases_unassigned_critical: number;
            /** Trend Cases Created */
            trend_cases_created?: components["schemas"]["DailyPoint"][];
            /** Trend Cases Closed */
            trend_cases_closed?: components["schemas"]["DailyPoint"][];
            /** Trend Critical Alerts */
            trend_critical_alerts?: components["schemas"]["DailyPoint"][];
            /** Trend Audit Activity */
            trend_audit_activity?: components["schemas"]["DailyPoint"][];
        };
        /** CommentBody */
        CommentBody: {
            /** Text */
            text: string;
            /** Actor */
            actor: string;
        };
        /** DailyPoint */
        DailyPoint: {
            /** Date */
            date: string;
            /** Value */
            value: number;
        };
        /** DetectRequest */
        DetectRequest: {
            /** Invoices */
            invoices: components["schemas"]["InvoiceRow"][];
            /**
             * Detectors
             * @description Détecteurs à activer parmi : duplicates, thresholds, sanctions, decp_rbe
             */
            detectors?: string[];
        };
        /** DetectResponse */
        DetectResponse: {
            /** N Invoices */
            n_invoices: number;
            /** N Findings */
            n_findings: number;
            /** Findings */
            findings: components["schemas"]["p2p_fraud__api__main__FindingOut"][];
            /** Run At */
            run_at: string;
        };
        /** GraphEdge */
        GraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvoiceRow */
        InvoiceRow: {
            /** Invoice Id */
            invoice_id: string;
            /** Vendor Name */
            vendor_name: string;
            /** Amount */
            amount: number;
            /** Invoice Date */
            invoice_date: string;
            /** Siren */
            siren?: string | null;
            /** Iban */
            iban?: string | null;
            /** Po Number */
            po_number?: string | null;
            /** User Id */
            user_id?: string | null;
            /** Gl Account */
            gl_account?: string | null;
            /** Cost Center */
            cost_center?: string | null;
            /**
             * Currency
             * @default EUR
             */
            currency: string;
        };
        /** NarrativeBody */
        NarrativeBody: {
            /** Vendor Id */
            vendor_id: string;
            /** Vendor Name */
            vendor_name?: string | null;
            /** Siren */
            siren?: string | null;
            /** Total Paid Eur */
            total_paid_eur?: number | null;
            /**
             * N Invoices
             * @default 0
             */
            n_invoices: number;
            /**
             * Is Sanctioned
             * @default false
             */
            is_sanctioned: boolean;
            /**
             * Is Pep
             * @default false
             */
            is_pep: boolean;
            /** Findings */
            findings?: {
                [key: string]: unknown;
            }[];
            /** Api Key */
            api_key?: string | null;
        };
        /** RingsGraph */
        RingsGraph: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
            /** N Shared Iban Rings */
            n_shared_iban_rings: number;
            /** N Vendor Clusters */
            n_vendor_clusters: number;
            /** Largest Cluster Size */
            largest_cluster_size: number;
            /** Scenario */
            scenario: string;
        };
        /** ScoreRequest */
        ScoreRequest: {
            /** Invoices */
            invoices: components["schemas"]["InvoiceRow"][];
            /** Detector Weights */
            detector_weights?: {
                [key: string]: number;
            } | null;
        };
        /** ScoreResponse */
        ScoreResponse: {
            /** N Invoices */
            n_invoices: number;
            /** Scores */
            scores: components["schemas"]["ScoreRow"][];
            /** Run At */
            run_at: string;
        };
        /** ScoreRow */
        ScoreRow: {
            /** Invoice Id */
            invoice_id: string;
            /** Score */
            score: number;
            /** Findings Count */
            findings_count: number;
            /** Reason Codes Fr */
            reason_codes_fr: string[];
        };
        /** TimelineEvent */
        TimelineEvent: {
            /** At */
            at: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Amount Eur */
            amount_eur?: number | null;
            /** Severity */
            severity?: string | null;
        };
        /** TopVendor */
        TopVendor: {
            /** Vendor Id */
            vendor_id: string;
            /** Vendor Name */
            vendor_name?: string | null;
            /** Exposure Eur */
            exposure_eur: number;
            /** N Findings */
            n_findings: number;
            /** Max Severity */
            max_severity: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VendorSummary */
        VendorSummary: {
            /** Vendor Id */
            vendor_id: string;
            /** Vendor Name */
            vendor_name?: string | null;
            /** Siren */
            siren?: string | null;
            /** Total Paid Eur */
            total_paid_eur?: number | null;
            /**
             * N Invoices
             * @default 0
             */
            n_invoices: number;
            /**
             * Is Sanctioned
             * @default false
             */
            is_sanctioned: boolean;
            /**
             * Is Pep
             * @default false
             */
            is_pep: boolean;
        };
        /** FindingOut */
        p2p_fraud__api__main__FindingOut: {
            /** Invoice Id */
            invoice_id: string;
            /** Detector */
            detector: string;
            /** Rule Id */
            rule_id: string;
            /** Severity */
            severity: string;
            /** Signal */
            signal: string;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /** Detected At */
            detected_at: string;
        };
        /** FindingOut */
        p2p_fraud__api__v1__FindingOut: {
            /** Invoice Id */
            invoice_id: string;
            /** Rule Id */
            rule_id: string;
            /** Severity */
            severity: string;
            /** Signal */
            signal: string;
            /** Detector */
            detector: string;
            /** Detected At */
            detected_at: string;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_oidc_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    callback_oidc_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
                error?: string | null;
                error_description?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                p2pfd_oidc_state?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_oidc_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_oidc_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                p2pfd_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cockpit_kpis_api_v1_cockpit_kpis_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CockpitKPIs"];
                };
            };
        };
    };
    cockpit_top_vendors_api_v1_cockpit_top_vendors_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopVendor"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_findings_api_v1_findings_get: {
        parameters: {
            query?: {
                rule_id?: string | null;
                severity?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["p2p_fraud__api__v1__FindingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vendor_summary_api_v1_vendors__vendor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vendor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VendorSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vendor_timeline_api_v1_vendors__vendor_id__timeline_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                vendor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_v1_api_v1_cases_get: {
        parameters: {
            query?: {
                status?: string | null;
                severity?: string | null;
                assignee?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOutV1"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    case_comment_api_v1_cases__case_id__comment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cases_bulk_assign_api_v1_cases_bulk_assign_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkAssignBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cases_bulk_close_api_v1_cases_bulk_close_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkCloseBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rings_graph_api_v1_rings_get: {
        parameters: {
            query?: {
                scenario?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RingsGraph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_list_api_v1_audit_get: {
        parameters: {
            query?: {
                cursor?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_verify_api_v1_audit_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditVerifyResult"];
                };
            };
        };
    };
    export_dossier_pdf_api_v1_exports_dossier_pdf_get: {
        parameters: {
            query: {
                case_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/pdf": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_narrative_stream_api_v1_llm_narrative_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NarrativeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    security_public_key_security_public_key_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    webhook_test_webhook_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    detect_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_csv_detect_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_detect_csv_detect_csv_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_cases_get: {
        parameters: {
            query?: {
                status_filter?: string | null;
                severity?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_case_cases__case_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
